"""The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

https://projecteuler.net/problem=12"""

def generador(n = 5):
    genesis = 1
    listado = [genesis]
    for i in range(2, n + 1):
        listado.append(i + listado[-1])
   
    return(listado)


def divisores(cantidad = 5):

    j = 0
    
    while 1:
        divisores = 0
        for k in range(1, 1 + (generador(j+1)[j])):
            if generador(j+1)[j] % k == 0:
                divisores += 1

        if divisores > cantidad:
            return generador(j+1)[j]
                    
        j += 1
        


print(divisores(90))
    
